experiment_name: grbal_half_cheetah
algo: grbal
env: HalfCheetahCustom-v0
seed: 42

train:
  device: cuda
  total_iterations: 50       # "epochs" in Table 3
  num_rollouts: 64           # ≈64k transitions per iteration (T × #Tasks/itr)
  max_path_length: 1000      # T in Table 3
  meta_updates_per_iter: 32  # #Tasks/itr (tasks used to meta-update)
  meta_batch_size: 32        # match #Tasks/itr
  adapt_window: 32           # M
  target_window: 32          # K
  hidden_sizes: [512, 512]
  inner_lr: 0.01             # inner learning rate ψ
  learnable_inner_lr: true
  outer_lr: 0.001            # outer learning rate
  second_order: true
  horizon: 10                # H_train
  n_candidates: 1000         # n_A train
  discount: 1.0
  gamma: 1.0

eval:
  episodes: 10
  seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  deterministic: true
  save_csv: true
  horizon: 15                # H_test
  n_candidates: 2500         # n_A test
