experiment_name: mb_cheetah
algo: mb_mpc
device: auto

environment:
  id: HalfCheetahTerrain-v0
  max_episode_length: 1000
  exclude_current_positions_from_observation: false

train:
  seed: 42
  steps_per_iteration: 20_000
  iterations: 50
  train_epochs: 50
  batch_size: 512
  valid_split_ratio: 0.1

  dynamics_model:
    hidden_sizes: [512, 512, 512]
    learning_rate: 0.001

  planner:
    type: "cem"
    horizon: 15
    n_candidates: 1000
    discount: 1.0
    num_cem_iters: 5
    percent_elites: 0.1
    alpha: 0.1

  perturbation:
    type: terrain
    probability: 1
    terrain_candidate: [gentle, basin]

eval:
  episodes: 10
  seeds: [0, 1, 2, 3]

  perturbation:
    type: terrain
    probability: 1
    terrain_candidate: [hill, steep]
