experiment_name: mb_mpc_HalfCheetah
algo: mb_mpc
env: HopperCustom-v0 #HopperCustom-v0 HalfCheetahCustom-v0

train:
  seed: 42

  max_path_length: 1000

  # --- pretrain phase (random data only) ---
  init_random_steps: 40_000
  epochs: 10
  batch_size: 512
  learning_rate: 0.001

  # --- dynamics model ---
  hidden_sizes: [256, 256]

  # --- mpc planner ---
  horizon: 12
  n_candidates: 1_000
  discount: 0.99

  # --- outer training loop ---
  rollout_steps: 2_500
  iterations: 20

eval:
  # --- evaluation phase ---
  episodes: 1
  seeds: [0,1,2,3,4,5,6,7,8,9]
