experiment_name: mb_mpc_HC_exploreWide_c4k
algo: mb_mpc
env: HalfCheetahCustom-v0 #HopperCustom-v0 HalfCheetahCustom-v0

train:
  seed: 42
  max_path_length: 1000
  total_env_steps: 130_000
  steps_per_update: 1_300
  warmup_fraction: 0.22

  # --- pretrain phase (random data only) ---

  epochs: 110
  batch_size: 512
  learning_rate: 0.0016

  # --- dynamics model ---
  hidden_sizes: [512, 512]

  # --- mpc planner ---
  horizon: 16
  n_candidates: 4_000
  discount: 0.99

  # --- outer training loop ---

eval:
  # --- evaluation phase ---
  episodes: 1
  seeds: [0,1,2,3,4,5,6,7,8,9]
