experiment_name: mb_mpc_HC_longHor_h20_c3k
algo: mb_mpc
env: HalfCheetahCustom-v0 #HopperCustom-v0 HalfCheetahCustom-v0

train:
  seed: 42
  max_path_length: 1000
  total_env_steps: 120_000
  steps_per_update: 1_500
  warmup_fraction: 0.15

  # --- pretrain phase (random data only) ---

  epochs: 120
  batch_size: 512
  learning_rate: 0.0018

  # --- dynamics model ---
  hidden_sizes: [512, 512, 256]

  # --- mpc planner ---
  horizon: 20
  n_candidates: 3_000
  discount: 0.99

  # --- outer training loop ---

eval:
  # --- evaluation phase ---
  episodes: 1
  seeds: [0,1,2,3,4,5,6,7,8,9]
