experiment_name: mbmpc_halfcheetah_v5
algo: mb_mpc
env: HalfCheetahCustom-v0
seed: 42  # Added for Nagabandi fidelity

train:
  total_iterations: 8
  # Prefer episode-based collection to match original MB-MPC
  num_rollouts: 10
  max_path_length: 100
  # Legacy step-based (ignored if num_rollouts set)
  init_random_steps: 2000
  rollout_steps: 12000
  epochs: 40
  # Dynamics + planner hyperparameters
  hidden_sizes: [512, 512]
  lr: 0.001
  batch_size: 128
  val_ratio: 0.1
  norm_eps: 1e-10
  gamma: 1.0
  device: cuda
  # Added for Nagabandi fidelity
  rolling_average_persitency: 0.99
  use_ema_early_stop: true
  use_reward_model: false
  discount: 1.0
  # CEM/RS settings
  # Explicit RS settings matching Nagabandi
  horizon: 30
  n_candidates: 5000
  # CEM options omitted for RS
  n_envs: 4  # Fewer envs here to balance heavier planner load & perturbations

  perturbation:
    type: action_scaling       # or actuator_fault, action_multiplier, joint_fault
    probability: 0.2
    effected_action_indices: [1, 2, 3, 4] # match action shape 
    range: [0.0, 1.5]

eval:
  episodes: 1
  seeds: [0, 1, 2, 3, 4, 5]
  deterministic: true
  save_csv: true

  perturbation:
    type: action_scaling       # or actuator_fault, action_multiplier, joint_fault
    probability: 1
    effected_action_indices: [0]
    range: [0.0, 1.5]

