experiment_name: mb_mpc_half_cheetah_mppi_buffers
algo: mb_mpc
env: HalfCheetahCustom-v0
seed: 42  # Added for Nagabandi fidelity

train:
  total_iterations: 50
  planner_type: mppi
  # Prefer episode-based collection to match original MB-MPC
  num_rollouts: 64
  max_path_length: 1000
  epochs: 50
  gamma: 1.0                 # evaluation discount (undiscounted scoring)

  # Dynamics + planner hyperparameters
  hidden_sizes: [512, 512]
  lr: 0.001
  batch_size: 500
  val_ratio: 0.1
  norm_eps: 1e-10            # normalization epsilon to match TF
  device: cuda

  # Added for Nagabandi fidelity
  rolling_average_persitency: 0.99
  use_ema_early_stop: false
  use_reward_model: false
  discount: 1.0              # planner return discount (default Nagabandi)
  mppi_lambda: 1.0
  mppi_std: null             # optional per-action std (float or list); defaults to 0.5 * action range

  # CEM/RS settings
  # Explicit RS settings matching Nagabandi
  horizon: 10
  n_candidates: 1000

  n_envs: 8

eval:
  episodes: 1
  seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  deterministic: true
  save_csv: true
