experiment_name: mb_mpc_HC_lowWarm_w10_su2k
algo: mb_mpc
env: HalfCheetahCustom-v0 #HopperCustom-v0 HalfCheetahCustom-v0

train:
  seed: 42
  max_path_length: 1000
  total_env_steps: 100_000
  steps_per_update: 2_000
  warmup_fraction: 0.1

  # --- pretrain phase (random data only) ---

  epochs: 100
  batch_size: 512
  learning_rate: 0.002

  # --- dynamics model ---
  hidden_sizes: [512, 512]

  # --- mpc planner ---
  horizon: 15
  n_candidates: 2_500
  discount: 0.99

  # --- outer training loop ---

eval:
  # --- evaluation phase ---
  episodes: 10
  seeds: [0,1,2,3,4,5,6,7,8,9]
