experiment_name: ppo_hopper
algo: ppo
env: HopperCustom-v0
seed: 42

train:
  n_envs: 16                # vectorized envs for throughput
  total_iterations: 160     # each iteration = n_envs * n_steps steps
  learning_rate: 0.0002     # slightly lower for stability
  n_steps: 4096             # longer rollouts per env
  batch_size: 256           # larger batch for stability
  n_epochs: 20              # more optimization passes per batch
  gamma: 0.99
  clip_range: 0.2

eval:
  episodes: 10
  seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  deterministic: true
  save_csv: true