experiment_name: ppo_halfcheetah
algo: ppo
env: HalfCheetahCustom-v0

train:
  n_envs: 16                # vectorized envs for throughput
  total_timesteps: 10_000_000  # aim for 10M steps for elegance
  learning_rate: 0.0002     # slightly lower for stability
  n_steps: 4096             # longer rollouts per env
  batch_size: 256           # larger batch for stability
  n_epochs: 20              # more optimization passes per batch
  gamma: 0.99
  clip_range: 0.2

eval:
  episodes: 10
  seeds: [0, 1, 2, 3, 4]
  deterministic: true
  save_csv: true
