experiment_name: ppo_half_cheetah_perturbation
algo: ppo
env: HalfCheetahCustom-v0
seed: 42

train:
  n_envs: 16                # vectorized envs for throughput
  total_iterations: 160     # each iteration = n_envs * n_steps steps
  learning_rate: 0.0002     # slightly lower for stability
  n_steps: 4096             # longer rollouts per env
  batch_size: 256           # larger batch for stability
  n_epochs: 20              # more optimization passes per batch
  gamma: 0.99
  clip_range: 0.2

  perturbation:
    type: action_scaling
    probability: 1
    effected_action_indices: [1,2,3,4,5]
    range: [0.0, 0.0]


eval:
  episodes: 10
  seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  deterministic: true
  save_csv: true

  perturbation:
    type: action_scaling
    probability: 1
    effected_action_indices: [0]
    range: [0.0, 0.0]
