experiment_name: trpo_half_cheetah_perturbation
algo: trpo
env: HalfCheetahCustom-v0
seed: 42

train:
  total_iterations: 600
  batch_size: 50000
  cg_iters: 10
  cg_damping: 0.1
  max_kl: 0.01
  gamma: 0.99
  lam: 0.97
  device: cuda
  n_envs: 8

  perturbation:
    type: action_scaling
    probability: 1
    effected_action_indices: [1,2,3,4,5]
    range: [0.0, 0.0]

eval:
  episodes: 10
  seeds: [0, 1, 2, 3, 4]
  save_csv: true

  perturbation:
    type: action_scaling
    probability: 1
    effected_action_indices: [0]
    range: [0.0, 0.0]
