experiment_name: ts_all_params_front_left
algo: ts_all_params
device: auto # cpu or cuda

environment:
  id: "FaithfulAnt-v0"
  max_episode_length: 500
  exclude_current_positions_from_observation: false

train:
  seed: 42 # Global RNG seed for reproducibility
  epochs: 10
  learning_rate: 0.0001
  eval_split: 0.2
  batch_size: 256

  dataset_path: global/D1/homes/ismailou/l2ra/learning_to_re_adapt/00_BASE/collected_data/cripple_front_left.npz  # [2, 3]

  pretrained_dynamics_model:
    model_path:  "global/D1/homes/ismailou/l2ra/learning_to_re_adapt/00_BASE/base_mb/model.pt"
    config_path: "global/D1/homes/ismailou/l2ra/learning_to_re_adapt/00_BASE/base_mb/config.yaml"


eval:
  eval_policy_rollout: true
  episodes: 5
  seeds: [42]

  perturbation:
    type: cripple
    probability: 1
    candidate_action_indices: [[2, 3]]
