experiment_name: tsra_1_short_eps
algo: tsra
env: GymAnt-v0 #GymAnt-v5
device: auto # cpu or cuda
exclude_current_positions_from_observation: true


train:
  seed: 42 # Global RNG seed for reproducibility
  max_episode_length: 200 # Max steps per episode rollout during data collection
  data_collection_policy: planner # random | base | planner
  eval_interval_steps: 0

  iterations: 100
  steps_per_iteration: 200
  train_epochs: 1
  batch_size: 256
  valid_split_ratio: 0.1

  pretrained_dynamics_model:
    model_path:  "/global/D1/homes/ismailou/l2ra/learning_to_re_adapt/outputs/2026-03-05/mb_mpc_robust_sweep_08_p20_low_noise/model.pt"
    config_path: "/global/D1/homes/ismailou/l2ra/learning_to_re_adapt/outputs/2026-03-05/mb_mpc_robust_sweep_08_p20_low_noise/config.yaml"

  residual_adapter:
     hidden_sizes: [128, 128]
     learning_rate: 0.00001
     enabled: true

  planner:
    type: "cem"
    horizon: 15
    n_candidates: 250
    discount: 0.99
    num_cem_iters: 4
    percent_elites: 0.15
    alpha: 0.20

  perturbation:
    type: action_inversion
    probability: 1
    candidate_action_indices: [1]
    
eval:
  episodes: 1 # Number of episodes to run per seed
  seeds: [0,1,2,3,4] # Evaluation seeds
  k_list: [1,5,10,15]


  perturbation:
    type: action_inversion
    probability: 1
    candidate_action_indices: [1]